on: [push]
name: Run tests
jobs:
  tests:
    name: Run tests on Rails 2.6
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1
      - uses: actions/setup-ruby@1
        with:
          ruby-version: 2.6.x
      - name: Bundle
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
